# Generated by Django 4.2.2 on 2023-07-17 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_add_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='momo',
            new_name='memo',
        ),
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 6, 55, 53, 23981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 6, 55, 53, 23931, tzinfo=datetime.timezone.utc)),
        ),
    ]
